### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by boboxx** [Jay-Tech/ioSenderTouch#8]
I'm unable to launch the app on a new install of Windows 11. I'm running ioSender Touch version 1.0.04. I can run ioSender 2.0.44 no problem.

this is the error I get after confirming the app config file creation:

![Screenshot 2024-03-02 212653](https://github.com/Jay-Tech/ioSenderTouch/assets/15091037/cbabf50e-ae7b-45ba-807c-fb35b2836bc8)

I do see app.config in the config folder so the app is able to run but it's not liking somehting!

**Comment by Jay-Tech** [comment]
I can not get this to happen, testing on Win 11 .  If you run it withought the app config the first time are you getting to the connection popup. 
![image](https://github.com/Jay-Tech/ioSenderTouch/assets/25882726/69afbe80-b66d-45d7-90c6-4817a08f8997)
Also if able can you grab some of the start up info from IO sender like 
![image](https://github.com/Jay-Tech/ioSenderTouch/assets/25882726/a441cbb5-09e7-47b3-816a-8f9abcc9b5c3)

**Comment by boboxx** [comment]
Yes I can see the com port selection and my controller is listed (COM3 CH340). The error is happening after that.

[VER:1.1f.20240226:]
[OPT:VNMZHSL2,100,1024,3,0]
[AXS:3:XYZ]
[NEWOPT:ENUMS,RT+,HOME,REBOOT,SED,RTC,WIFI,FTP,SD]
[FIRMWARE:grblHAL]
[SIGNALS:RHSP]
[NVS STORAGE:*FLASH]
[FREE MEMORY:139K]
[DRIVER:ESP32]
[DRIVER VERSION:240224]
[DRIVER OPTIONS:4.3.2]
[BOARD:MKS Tinybee V1.0]
[AUX IO:1,0,0,0]
[WIFI MAC:d8:bc:38:48:ab:cc]
[IP:10.10.10.7]
[PLUGIN:MODBUS v0.15]
[PLUGIN:HUANYANG VFD v0.11]
[PLUGIN:SDCARD v1.13]
[PLUGIN:FS macro plugin v0.07]
[SPINDLE:Huanyang v1]
ok

**Comment by Jay-Tech** [comment]
Here is a verison with logging to maybe help find the area that has the issues.  It will write a log file to 
![image](https://github.com/Jay-Tech/ioSenderTouch/assets/25882726/62c434d8-1983-489d-9bcd-e395a205445b)

and look somethign like this 

![image](https://github.com/Jay-Tech/ioSenderTouch/assets/25882726/39668333-b57c-499e-96bf-a0b6c841cadc)

[isSender TouchV1.0.04-D.zip](https://github.com/Jay-Tech/ioSenderTouch/files/14473295/isSender.TouchV1.0.04-D.zip)

**Comment by boboxx** [comment]
Using the version posted, I get the com port selection but there are no ErrorLog file that gets created and the main windows never shows up. I can see the task running.

I installed VisualStudio and was going to build and debug from source but that seems to have resoled the issue so there must be a reference that was missing on a fresh install.

**Comment by Jay-Tech** [comment]
wierd your throwing an exception showing in a popup  that makes it seems like something in the main widow startup but its not logging anything when wrapping all that startup with try catches and logging .  Guess  VS must have installed/updated some .dll or .net package that was missing ?
